name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Version
        run: |
          VERSION="${{ github.ref_name }}"
          sed -i "s/@@VERSION@@/$VERSION/g" recolor_pdf.sh

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: recolor_pdf.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
